defaults:
  run:
    shell: bash
env:
  BRANCH_NAME: main
  DEPLOY_ENV: production
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v3
    - uses: actions/setup-java@v3
    - run: echo Building...
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v3
    - uses: actions/setup-java@v3
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v3
    - uses: actions/setup-java@v3
    - run: echo Running tests...
    strategy:
      matrix:
        node_version:
        - '12'
        - '14'
        - '16'
        os:
        - ubuntu-latest
        - windows-latest
name: CI
'on':
- push
- pull_request
