defaults:
  run:
    shell: bash
jobs:
  build:
    steps:
    - run: echo Running in Python version ${{ matrix.python }}
    - run: echo Building...
    strategy:
      matrix:
        python:
        - '3.7'
        - '3.8'
        - '3.9'
  deploy:
    steps: []
  test:
    steps:
    - run: echo Running tests...
name: CI
'on':
- push
- pull_request
